<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Romina Gutiérrez Cortés

**Fecha:** 04 de noviembre del 2020.

**Expediente** : 713415.
**Profesor:** Oscar David Jaramillo Zuluaga.

# Tarea 8: Clase 17

# Ejercicio
Para ver si la venta de chips de silicio son independientes del punto del ciclo de negocios en que se encuentre la economía del país se han recogido las ventas semanales de una empresa y datos acerca de la economía del país, y se reportan los siguientes resultados:
![imagen.png](attachment:imagen.png)

Realice la prueba de chi-cuadrado para validar la independencia del punto del ciclo de negocios en que se encuentre la economía.

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st     
import matplotlib.pyplot as plt

In [13]:
data = pd.DataFrame(index=['Pico','Abajo','Subiendo','Bajando','Total'],columns=['Alta','Mediana','Baja','Total'])
data.iloc[0,:-1] = [20,7,3]
data.iloc[1,:-1] = [30,40,30]
data.iloc[2,:-1] = [20,8,2]
data.iloc[3,:-1] = [30,5,5]
data.iloc[4,:-1] = data.sum(axis=0)
data['Total'] = data.sum(axis=1)
data

Alta Mediana Baja  Total
Pico       20       7    3   30.0
Abajo      30      40   30  100.0
Subiendo   20       8    2   30.0
Bajando    30       5    5   40.0
Total     100      60   40  200.0

In [34]:
P_pico = data.iloc[0,3]/data.iloc[-1,-1]
P_abajo = data.iloc[1,3]/data.iloc[-1,-1]
P_subiendo = data.iloc[2,3]/data.iloc[-1,-1]
f_o = data.loc[data.index!='Total',data.columns!='Total'].values.flatten()
f_e = np.concatenate([data.iloc[-1,:-1]*(P_pico),data.iloc[-1,:-1]*(P_abajo),data.iloc[-1,:-1]*(P_subiendo),data.iloc[-1,:-1]*(1-(P_pico+P_abajo+P_subiendo))])

f_e,f_o

(array([15.0, 9.0, 6.0, 50.0, 30.0, 20.0, 15.0, 9.0, 6.0,
        19.999999999999996, 11.999999999999996, 7.999999999999998],
       dtype=object),
 array([20, 7, 3, 30, 40, 30, 20, 8, 2, 30, 5, 5], dtype=object))

In [42]:
F_obse = f_o 
F_espe = f_e 
x2 = st.chisquare(F_obse,F_espe,ddof=3)
print('Valor de chi cuadrado = ',list(x2)[0],',p-value de la prueba=',list(x2)[1])

Ji = st.chi2.ppf(q = 0.9,df=3)
print('Estadístico de Ji = ',Ji)

Valor de chi cuadrado =  34.59722222222222 ,p-value de la prueba= 3.1653811153460315e-05
Estadístico de Ji =  6.251388631170325


In [44]:
x1 = st.chi2.cdf(list(x2)[0],df=3)
x1

0.9999998518101967

Rechazamos que el nivel de las ventas sea independiente del ciclo de negocios de la economía del país, ya que el valor de $$X_i^2$$ quedó más allá de nuestro valor crítico.


###### Ejercicio 2: prueba de chi cuadrada de homogeneidad
En un estudio a los habitos de television de los ninos, se selecciona una muestra aleatoria de 300 personas (100 ninos y 200 ninas). A cada infante se le pregunta que es mejor the lone ranger, sesame street o los simpson. Y se obtienen los siguientes resultados.


Realice la prueba de chi-cuadrado para validar la homogeneidad. Las preferencias de los hombres difieren significativa de las ninas, usa 0.05 de nivel de significancia.
Las hipotesis que se definen son las siguientes:

H0: A los niños les gustan lone ranger = A las niñas les gustan lone ranger

H0: A los niños les gustan sesame street = A las niñas les gustan lone ranger

H0: A los niños les gustan sesame street = A las niñas les gustan los simpsons

H1: No se cumple al menos una de las hipotesis nulas.


In [53]:
GDL2 = 2
datos2 = pd.DataFrame(index = ['Boys', 'Girls', 'Total 1'],
                      columns = ['Lone Ranger', 'Sesame Street', 'The Simpsons', 'Total _'])
datos2.iloc[0,:-1] = (50,30,20)
datos2.iloc[1,:-1] = (50,80,70)
datos2['Total _'] = datos2.sum(axis = 1)
datos2.loc['Total 1'] = datos2.sum(axis = 0)
datos2

Lone Ranger Sesame Street The Simpsons  Total _
Boys             50            30           20    100.0
Girls            50            80           70    200.0
Total 1         100           110           90    300.0

In [61]:
P2 = datos2.iloc[:2,3]/datos2.iloc[-1,-1]
f_o2 = datos2.loc[datos2.index!='Total 1',datos2.columns!='Total _'].values.flatten()
f_e2 = np.concatenate([datos2.iloc[-1,:-1]*P2[0],datos2.iloc[-1,:-1]*P2[1]])

f_o2, f_e2

(array([50, 30, 20, 50, 80, 70], dtype=object),
 array([33.33333333333333, 36.666666666666664, 30.0, 66.66666666666666,
        73.33333333333333, 60.0], dtype=object))

In [65]:
x2 = st.chisquare(f_o2,f_e2,ddof=GDL2)
print('Valor de chi cuadrado = ',list(x2)[0],',p-value de la prueba=',list(x2)[1])

Ji = st.chi2.ppf(q = 0.95,df=GDL2)
print('Estadístico de Ji = ',Ji)

Valor de chi cuadrado =  19.31818181818182 ,p-value de la prueba= 0.00023495405224903583
Estadístico de Ji =  5.991464547107979


Debido a que el p-value < alpha(0.05), la Ho se rechaza. es decir las preferencias de los niños no son homogeneas respecto a las de las niñas 

#### 3)prueba de chi cuadrada de bondad ajuste


Acme Toy Company prints baseball cards. The company claims that 30% of the cards are rookies, 60% veterans but not All-Stars, and 10% are veteran All-Stars.

Suppose a random sample of 100 cards has 50 rookies, 45 veterans, and 5 All-Stars. Is this consistent with Acme's claim? Use a 0.05 level of significance.

Null hypothesis: The proportion of rookies, veterans, and All-Stars is 30%, 60% and 10%, respectively. \ Alternative hypothesis: At least one of the proportions in the null hypothesis is false.

In [66]:
alpha = 0.05

In [67]:
data_2 = pd.DataFrame(columns=['Proporciones', 'Random Sample'])
data_2['Proporciones'] = [0.30,0.60,0.10]
data_2['Random Sample'] = [50, 45, 5]
data_2


Proporciones  Random Sample
0           0.3             50
1           0.6             45
2           0.1              5

In [70]:
DF = 2
n = 100 
esp = np.array([0.30,0.60,0.10])
muestreo = np.array([50,45,5])

In [71]:
f_e3 = esp * n
f_o3 = muestreo

f_e3, f_o3

(array([30., 60., 10.]), array([50, 45,  5]))

In [75]:
F_obse_2 = f_o3 
F_espe_2 = f_e3

x2_2 = st.chisquare(F_obse_2, F_espe_2, ddof=1.99)
print('Valor de chi cuadrado = ',list(x2_2)[0],', p-value de la prueba=',list(x2_2)[1])

Ji_2 = st.chi2.ppf(q = 0.95, df=1.99)
print('Estadístico de Ji = ',Ji_2)

Valor de chi cuadrado =  19.583333333333336 , p-value de la prueba= 2.6486825286769527e-08
Estadístico de Ji =  5.97208204124762


In [76]:
x12_2 = st.chi2.cdf(list(x2_2)[0],df=1.99)
x12_2

0.9999449047857046

Se rechaza la hipotesis nula debido a que el p-value < alpha(0.05), la Ho se rechaza, es decir las cartas no son se distribuyen de la forma que dice Acme Toy.